import type { Spot } from '../types'

/** Beispieldaten für den Demo-Modus (ohne Supabase-Credentials). */
export const DEMO_SPOTS: Spot[] = [
  {
    id: 'demo-1',
    name: 'Café Frischluft',
    category: 'Café',
    address: 'Sendlinger Str. 12, 80331 München',
    district: 'Altstadt-Lehel',
    has_ac: true,
    wifi: true,
    price_category: '€€',
    highlights: 'Eiskalt im Sommer, ruhige Atmosphäre, exzellenter Flat White.',
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=Caf%C3%A9+Frischluft+M%C3%BCnchen',
    submitted_by: 'Lena',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    verified: true,
  },
  {
    id: 'demo-2',
    name: 'Polar Works',
    category: 'Co-Working',
    address: 'Landwehrstr. 30, 80336 München',
    district: 'Ludwigsvorstadt-Isarvorstadt',
    has_ac: true,
    wifi: true,
    price_category: '€€',
    highlights: 'Starke Klima, schnelles WLAN, Steckdosen an jedem Platz. Perfekt für Deep Work.',
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=Polar+Works+M%C3%BCnchen',
    submitted_by: 'Anonym',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    verified: false,
  },
  {
    id: 'demo-3',
    name: 'Trattoria Tramontana',
    category: 'Restaurant',
    address: 'Türkenstr. 80, 80799 München',
    district: 'Maxvorstadt',
    has_ac: true,
    wifi: false,
    price_category: '€€€',
    highlights: 'Angenehm kühl auch bei 35°C draußen. Top Pasta, freundlicher Service.',
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=Trattoria+Tramontana+M%C3%BCnchen',
    submitted_by: 'Max',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    verified: false,
  },
  {
    id: 'demo-4',
    name: 'Eisbar Schwabing',
    category: 'Bar',
    address: 'Leopoldstr. 50, 80802 München',
    district: 'Schwabing-West',
    has_ac: true,
    wifi: false,
    price_category: '€€',
    highlights: 'Cocktails & runtergekühlte Luft. Abends gut besucht.',
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=Eisbar+Schwabing+M%C3%BCnchen',
    submitted_by: 'Jonas',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    verified: false,
  },
]
